# Rust / CARGO
if [ -f $HOME/.cargo/env ]
then
    . "$HOME/.cargo/env"
fi

# Apollo rover
#source "/Users/csaba/.rover/env"


# # NVM
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# [ -s "$BREW_HOME/opt/nvm/nvm.sh" ] && \. "$BREW_HOME/opt/nvm/nvm.sh"
# if [[ $SHELL == *bash ]]
# then
#        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
# fi
