brew "ykman"
cask "yubico-yubikey-manager"
cask "telegram"
cask "signal"
cask "keybase"
cask "discord"
cask "obsidian"
cask "Grammarly"
cask "microsoft-teams"
cask "vlc"

# cask "google-drive"
# cask "zoom"
# cask "slack"

# cask "wacom-tablet"
# cask "loupedeck"

# brew "ledger-live"
# brew "keepassxc"

# LIBS


